export type BasicCommandKind = "statement" | "function" | "operator"

export interface BasicCommandEntry {
  id: string
  kind: BasicCommandKind
  label: string
  syntax: string
  description: string
  insertSnippet: string
  searchTokens: string[]
}

export const BASIC_COMMAND_ENTRIES: BasicCommandEntry[] = [
  {
    id: "stmt-rem",
    kind: "statement",
    label: "REM comment",
    syntax: "REM text",
    description: "Comment statement.",
    insertSnippet: "REM ${1:comment}",
    searchTokens: ["rem", "comment", "remark"],
  },
  {
    id: "stmt-apostrophe",
    kind: "statement",
    label: "' comment",
    syntax: "' text",
    description: "Comment alias for REM.",
    insertSnippet: "' ${1:comment}",
    searchTokens: ["apostrophe", "comment", "rem"],
  },
  {
    id: "stmt-end",
    kind: "statement",
    label: "END",
    syntax: "END",
    description: "Stop program execution",
    insertSnippet: "END",
    searchTokens: ["end", "stop", "halt"],
  },
  {
    id: "stmt-stop",
    kind: "statement",
    label: "STOP",
    syntax: "STOP",
    description: "Stop program execution",
    insertSnippet: "STOP",
    searchTokens: ["stop", "halt", "end"],
  },
  {
    id: "stmt-cls",
    kind: "statement",
    label: "CLS",
    syntax: "CLS",
    description: "Clear the screen",
    insertSnippet: "CLS",
    searchTokens: ["cls", "clear", "screen"],
  },
  {
    id: "stmt-cls-color",
    kind: "statement",
    label: "CLS color",
    syntax: "CLS colorExpr",
    description: "Clear screen and fill with color expression.",
    insertSnippet: "CLS ${1:0}",
    searchTokens: ["cls", "clear", "color"],
  },
  {
    id: "stmt-color",
    kind: "statement",
    label: "COLOR",
    syntax: "COLOR fg,bg",
    description: "Set foreground/background color",
    insertSnippet: "COLOR ${1:7},${2:0}",
    searchTokens: ["color", "fg", "bg", "palette"],
  },
  {
    id: "stmt-locate",
    kind: "statement",
    label: "LOCATE",
    syntax: "LOCATE col,row",
    description: "Move cursor to column,row",
    insertSnippet: "LOCATE ${1:0},${2:0}",
    searchTokens: ["locate", "cursor", "position", "col", "row"],
  },
  {
    id: "stmt-print",
    kind: "statement",
    label: "PRINT",
    syntax: "PRINT expr",
    description: "Print text or expression",
    insertSnippet: "PRINT ${1:\"HELLO\"}",
    searchTokens: ["print", "output", "display", "text"],
  },
  {
    id: "stmt-print-semicolon",
    kind: "statement",
    label: "PRINT ; separator",
    syntax: "PRINT expr1;expr2",
    description: "Print expressions without tab spacing.",
    insertSnippet: "PRINT ${1:expr1};${2:expr2}",
    searchTokens: ["print", "semicolon", ";", "separator"],
  },
  {
    id: "stmt-print-comma",
    kind: "statement",
    label: "PRINT , separator",
    syntax: "PRINT expr1,expr2",
    description: "Print expressions with tab spacing.",
    insertSnippet: "PRINT ${1:expr1},${2:expr2}",
    searchTokens: ["print", "comma", ",", "separator", "tab"],
  },
  {
    id: "stmt-input",
    kind: "statement",
    label: "INPUT",
    syntax: "INPUT \"prompt\";var",
    description: "Prompt user for value",
    insertSnippet: "INPUT ${1:\"PROMPT\"};${2:A$}",
    searchTokens: ["input", "prompt", "read", "ask"],
  },
  {
    id: "stmt-if-then-line",
    kind: "statement",
    label: "IF ... THEN line",
    syntax: "IF cond THEN #line",
    description: "Conditional branch to a line number.",
    insertSnippet: "IF ${1:cond} THEN #${2:10}",
    searchTokens: ["if", "then", "condition", "branch", "line"],
  },
  {
    id: "stmt-if-then-else",
    kind: "statement",
    label: "IF ... THEN ... ELSE",
    syntax: "IF cond THEN stmt ELSE stmt",
    description: "Conditional branch with fallback statement.",
    insertSnippet:
      "IF ${1:cond} THEN ${2:PRINT \"YES\"} ELSE ${3:PRINT \"NO\"}",
    searchTokens: ["if", "then", "else", "condition", "branch"],
  },
  {
    id: "stmt-goto",
    kind: "statement",
    label: "GOTO",
    syntax: "GOTO #line",
    description: "Jump to line number",
    insertSnippet: "GOTO #${1:10}",
    searchTokens: ["goto", "jump", "line"],
  },
  {
    id: "stmt-gosub",
    kind: "statement",
    label: "GOSUB",
    syntax: "GOSUB #line",
    description: "Call line as subroutine",
    insertSnippet: "GOSUB #${1:100}",
    searchTokens: ["gosub", "subroutine", "call", "line"],
  },
  {
    id: "stmt-return",
    kind: "statement",
    label: "RETURN",
    syntax: "RETURN",
    description: "Return from subroutine",
    insertSnippet: "RETURN",
    searchTokens: ["return", "gosub", "subroutine"],
  },
  {
    id: "stmt-for",
    kind: "statement",
    label: "FOR ... TO ...",
    syntax: "FOR var=start TO end",
    description: "Start counted loop.",
    insertSnippet: "FOR ${1:I}=${2:0} TO ${3:10}",
    searchTokens: ["for", "to", "loop", "counter"],
  },
  {
    id: "stmt-for-step",
    kind: "statement",
    label: "FOR ... TO ... STEP ...",
    syntax: "FOR var=start TO end STEP step",
    description: "Start counted loop with custom step.",
    insertSnippet: "FOR ${1:I}=${2:0} TO ${3:10} STEP ${4:1}",
    searchTokens: ["for", "to", "step", "loop", "counter"],
  },
  {
    id: "stmt-next",
    kind: "statement",
    label: "NEXT var",
    syntax: "NEXT var",
    description: "Advance counted loop with explicit variable.",
    insertSnippet: "NEXT ${1:I}",
    searchTokens: ["next", "for", "loop"],
  },
  {
    id: "stmt-next-plain",
    kind: "statement",
    label: "NEXT",
    syntax: "NEXT",
    description: "Advance most recent loop frame.",
    insertSnippet: "NEXT",
    searchTokens: ["next", "for", "loop"],
  },
  {
    id: "stmt-dim",
    kind: "statement",
    label: "DIM",
    syntax: "DIM name(size)",
    description: "Declare array size",
    insertSnippet: "DIM ${1:N}(${2:8})",
    searchTokens: ["dim", "array", "declare", "size"],
  },
  {
    id: "stmt-pset",
    kind: "statement",
    label: "PSET",
    syntax: "PSET x,y",
    description: "Draw a pixel at x,y using current color.",
    insertSnippet: "PSET ${1:X},${2:Y}",
    searchTokens: ["pset", "pixel", "draw", "graphics"],
  },
  {
    id: "stmt-pset-color",
    kind: "statement",
    label: "PSET color",
    syntax: "PSET x,y,color",
    description: "Draw a pixel at x,y with explicit color.",
    insertSnippet: "PSET ${1:X},${2:Y},${3:7}",
    searchTokens: ["pset", "pixel", "draw", "graphics", "color"],
  },
  {
    id: "stmt-line",
    kind: "statement",
    label: "LINE",
    syntax: "LINE x1,y1,x2,y2",
    description: "Draw line with current color.",
    insertSnippet: "LINE ${1:X1},${2:Y1},${3:X2},${4:Y2}",
    searchTokens: ["line", "draw", "graphics"],
  },
  {
    id: "stmt-line-color",
    kind: "statement",
    label: "LINE color",
    syntax: "LINE x1,y1,x2,y2,color",
    description: "Draw line with explicit color.",
    insertSnippet: "LINE ${1:X1},${2:Y1},${3:X2},${4:Y2},${5:7}",
    searchTokens: ["line", "draw", "graphics", "color"],
  },
  {
    id: "stmt-rect",
    kind: "statement",
    label: "RECT",
    syntax: "RECT x,y,w,h",
    description: "Draw rectangle with current color.",
    insertSnippet: "RECT ${1:X},${2:Y},${3:W},${4:H}",
    searchTokens: ["rect", "rectangle", "draw", "graphics"],
  },
  {
    id: "stmt-rect-color",
    kind: "statement",
    label: "RECT color",
    syntax: "RECT x,y,w,h,color",
    description: "Draw rectangle with explicit color.",
    insertSnippet: "RECT ${1:X},${2:Y},${3:W},${4:H},${5:7}",
    searchTokens: ["rect", "rectangle", "draw", "graphics", "color"],
  },
  {
    id: "stmt-let",
    kind: "statement",
    label: "LET assignment",
    syntax: "LET var=expr",
    description: "Assign value to variable",
    insertSnippet: "LET ${1:A}=${2:0}",
    searchTokens: ["let", "assignment", "variable", "="],
  },
  {
    id: "stmt-assignment",
    kind: "statement",
    label: "Assignment",
    syntax: "var=expr",
    description: "Assign value without LET keyword.",
    insertSnippet: "${1:A}=${2:0}",
    searchTokens: ["assignment", "let", "variable", "="],
  },
  {
    id: "fn-abs",
    kind: "function",
    label: "ABS",
    syntax: "ABS(expr)",
    description: "Absolute value.",
    insertSnippet: "ABS(${1:expr})",
    searchTokens: ["abs", "function", "math", "absolute"],
  },
  {
    id: "fn-asc",
    kind: "function",
    label: "ASC",
    syntax: "ASC(str$)",
    description: "ASCII code of first character.",
    insertSnippet: "ASC(${1:str$})",
    searchTokens: ["asc", "ascii", "function", "string"],
  },
  {
    id: "fn-chr",
    kind: "function",
    label: "CHR$",
    syntax: "CHR$(code)",
    description: "Character from ASCII code.",
    insertSnippet: "CHR$(${1:code})",
    searchTokens: ["chr$", "ascii", "function", "string", "character"],
  },
  {
    id: "fn-inkey",
    kind: "function",
    label: "INKEY$",
    syntax: "INKEY$",
    description: "Read buffered key input.",
    insertSnippet: "INKEY$",
    searchTokens: ["inkey$", "input", "keyboard", "function"],
  },
  {
    id: "fn-int",
    kind: "function",
    label: "INT",
    syntax: "INT(expr)",
    description: "Floor numeric expression.",
    insertSnippet: "INT(${1:expr})",
    searchTokens: ["int", "function", "math", "floor"],
  },
  {
    id: "fn-len",
    kind: "function",
    label: "LEN",
    syntax: "LEN(str$)",
    description: "Length of string.",
    insertSnippet: "LEN(${1:str$})",
    searchTokens: ["len", "function", "string", "length"],
  },
  {
    id: "fn-rnd-noarg",
    kind: "function",
    label: "RND",
    syntax: "RND()",
    description: "Random float in [0,1).",
    insertSnippet: "RND()",
    searchTokens: ["rnd", "random", "function"],
  },
  {
    id: "fn-rnd-max",
    kind: "function",
    label: "RND max",
    syntax: "RND(max)",
    description: "Random integer in [0,max).",
    insertSnippet: "RND(${1:max})",
    searchTokens: ["rnd", "random", "function", "max"],
  },
  {
    id: "fn-str",
    kind: "function",
    label: "STR$",
    syntax: "STR$(expr)",
    description: "Convert value to string.",
    insertSnippet: "STR$(${1:expr})",
    searchTokens: ["str$", "string", "function", "convert"],
  },
  {
    id: "fn-val",
    kind: "function",
    label: "VAL",
    syntax: "VAL(str$)",
    description: "Convert string to number.",
    insertSnippet: "VAL(${1:str$})",
    searchTokens: ["val", "string", "number", "function", "convert"],
  },
  {
    id: "op-eq",
    kind: "operator",
    label: "=",
    syntax: "left = right",
    description: "Equality comparison (also used in assignment).",
    insertSnippet: "${1:left} = ${2:right}",
    searchTokens: ["=", "equal", "comparison", "assignment"],
  },
  {
    id: "op-neq",
    kind: "operator",
    label: "<>",
    syntax: "left <> right",
    description: "Not-equal comparison.",
    insertSnippet: "${1:left} <> ${2:right}",
    searchTokens: ["<>", "not equal", "comparison"],
  },
  {
    id: "op-lt",
    kind: "operator",
    label: "<",
    syntax: "left < right",
    description: "Less-than comparison.",
    insertSnippet: "${1:left} < ${2:right}",
    searchTokens: ["<", "less than", "comparison"],
  },
  {
    id: "op-gt",
    kind: "operator",
    label: ">",
    syntax: "left > right",
    description: "Greater-than comparison.",
    insertSnippet: "${1:left} > ${2:right}",
    searchTokens: [">", "greater than", "comparison"],
  },
  {
    id: "op-lte",
    kind: "operator",
    label: "<=",
    syntax: "left <= right",
    description: "Less-than-or-equal comparison.",
    insertSnippet: "${1:left} <= ${2:right}",
    searchTokens: ["<=", "less or equal", "comparison"],
  },
  {
    id: "op-gte",
    kind: "operator",
    label: ">=",
    syntax: "left >= right",
    description: "Greater-than-or-equal comparison.",
    insertSnippet: "${1:left} >= ${2:right}",
    searchTokens: [">=", "greater or equal", "comparison"],
  },
  {
    id: "op-and",
    kind: "operator",
    label: "AND",
    syntax: "left AND right",
    description: "Logical conjunction.",
    insertSnippet: "${1:left} AND ${2:right}",
    searchTokens: ["and", "logical", "boolean"],
  },
  {
    id: "op-or",
    kind: "operator",
    label: "OR",
    syntax: "left OR right",
    description: "Logical disjunction.",
    insertSnippet: "${1:left} OR ${2:right}",
    searchTokens: ["or", "logical", "boolean"],
  },
  {
    id: "op-not",
    kind: "operator",
    label: "NOT",
    syntax: "NOT expr",
    description: "Logical negation.",
    insertSnippet: "NOT ${1:expr}",
    searchTokens: ["not", "logical", "boolean"],
  },
  {
    id: "op-mod",
    kind: "operator",
    label: "MOD",
    syntax: "left MOD right",
    description: "Remainder operator.",
    insertSnippet: "${1:left} MOD ${2:right}",
    searchTokens: ["mod", "remainder", "math", "operator"],
  },
]
